version: '3'
services:
    maverick:
        image:
            docker.io/furutanian/maverick
        container_name:
            maverick-beta
        build:
            context:
                .
#           args:
#               http_proxy: http://user_abc:password@proxy.example.com:8080/
#               https_proxy: http://user_abc:password@proxy.example.com:8080/
        ports:
            - 8081:80
        privileged:
            true
        environment:
            TZ: Asia/Tokyo
#           http_proxy: http://user_abc:password@proxy.example.com:8080/
#           https_proxy: http://user_abc:password@proxy.example.com:8080/
        volumes:
            - pv:/var/lib/pv
        command:
            bash -c 'bash startup.sh && /sbin/init'

# mkdir -p pv/mave しておくこと
volumes:
    pv:
        driver_opts:
            type: none
            device: /root/docker/maverick/pv
            o: bind

